function  WWHBookData_Files(P)
{
P.fA("InstallAnywhere 8.0","introduction.htm");
P.fA("Legal Information","legal_info.htm");
P.fA("Using Help","using_help.htm");
P.fA("Documentation Conventions","using_helpi.htm");
P.fA("Welcome to Macrovision","welcome.htm");
P.fA("Macrovision Solutions","macrovision_products.htm");
P.fA("Macrovision Professional Services","macrovision_professional_services.htm");
P.fA("Technical Support Resources","technical_support_resources.htm");
P.fA("Contacting Macrovision Corporation","contacting_macrovision_corporation.htm");
P.fA("Getting Started","getting_started.htm");
P.fA("Introductory Tutorial - Building an Installer","intro_tutorial.htm");
P.fA("Advanced Tutorial - Using the Advanced Designer","advanced_tutorial.htm");
P.fA("Editions","editions.htm");
P.fA("Registration","registration.htm");
P.fA("Project Conversion","project_conversion.htm");
P.fA("Key Concepts","key_concepts.htm");
P.fA("Authoring Environments","Authoring_Environments.htm");
P.fA("Project Wizard","Project_Wizard.htm");
P.fA("Advanced Designer","Advanced_Designer.htm");
P.fA("Installer Types","Installer_Types.htm");
P.fA("Installer Modes","Installer_Modes.htm");
P.fA("Install Set, Feature, and Components","Install_Set_Feature_and_Components_.htm");
P.fA("Install Sets","Install_Sets.htm");
P.fA("Features","Features.htm");
P.fA("Components","Shared_Components.htm");
P.fA("Installer Interface GUI","Installer_Interface_GUI.htm");
P.fA("Localization","Localization.htm");
P.fA("Look and Feel","Look_and_Feel.htm");
P.fA("Actions","Actions.htm");
P.fA("Rules","Rules_.htm");
P.fA("Uninstaller","Uninstaller.htm");
P.fA("LaunchAnywhere","LaunchAnywhere.htm");
P.fA("Magic Folders","Magic_Folders.htm");
P.fA("SpeedFolders","SpeedFolders.htm");
P.fA("InstallAnywhere Variables","InstallAnywhere_Variables.htm");
P.fA("Installer Sub-Projects: Merge Modules","Installer_Sub_Projects_Merge_Modules.htm");
P.fA("Action Groups","Action_Groups.htm");
P.fA("Templates","Templates.htm");
P.fA("Project File","Project_File.htm");
P.fA("Advanced Designer","advanced_designerao.htm");
P.fA("Project","Project.htm");
P.fA("Info","Info.htm");
P.fA("Description","Description.htm");
P.fA("File Settings","File_Settings.htm");
P.fA("Platforms","Platforms.htm");
P.fA("Locales","Locales.htm");
P.fA("Rules","Rules1.htm");
P.fA("Config","Config.htm");
P.fA("Java","Java.htm");
P.fA("Installer UI","Installer_UI.htm");
P.fA("Look &amp; Feel","installer%20look%20and%20feel.htm");
P.fA("Billboards","Billboards1.htm");
P.fA("Help","Help.htm");
P.fA("Organization","Organization.htm");
P.fA("Install Sets","Install_Sets1.htm");
P.fA("Features","Features1.htm");
P.fA("Components","Components1.htm");
P.fA("Modules","Modules.htm");
P.fA("DIM References","DIM_references.htm");
P.fA("Install","Install.htm");
P.fA("Visual Tree","Visual_Tree.htm");
P.fA("Assigning Files","Assigning_Files.htm");
P.fA("Assign to Product Features","Assign_to_Product_Features.htm");
P.fA("Assign to Components","Assign_to_Components.htm");
P.fA("Set Classpath","Set_Classpath1.htm");
P.fA("Add Launcher","Add_Launcher.htm");
P.fA("Pre and Post Install and Uninstall Tasks","Pre_and_Post_Install_and_Uninstall_Tasks.htm");
P.fA("Build","Build.htm");
P.fA("Build Targets","Build_Targets.htm");
P.fA("Distribution","Merge_Modules.htm");
P.fA("Build Log","MSI_Export.htm");
P.fA("Common Solutions","common_solutions.htm");
P.fA("Bundling Java Runtime Environments","Bundling_Java_Runtime_Environments.htm");
P.fA("Creating Launchers for Java Applications","Creating_Launchers_for_Java_Applications.htm");
P.fA("Organizing Features and Components","Organizing_Features_and_Components.htm");
P.fA("Best Practices for Components","Best_Practices_for_Components.htm");
P.fA("Adding Components","Adding_Components.htm");
P.fA("Assigning Files to Components","Assigning_Files_to_Components.htm");
P.fA("Removing Empty Components","Removing_Empty_Components.htm");
P.fA("Integrating Components Already Installed on Target System","Integrating_Components_Already_Installed_on_Target_System.htm");
P.fA("Adding Features","Adding_Features.htm");
P.fA("Assigning Components to Features","Assigning_Components_to_Features.htm");
P.fA("Improving Installation Performance","Improving_Installation_Performance.htm");
P.fA("Launching Additional Installers","Launching_Additional_Installers.htm");
P.fA("Digitally Signing Installers","Digitally_Signing_Installers.htm");
P.fA("Team Development","Team_Development.htm");
P.fA("How Source Paths Work","How_Source_Paths_Work.htm");
P.fA("Adding Source Paths","Adding_Source_Paths.htm");
P.fA("Updating the Location of Files and Resources","Updating_the_Location_of_Files_and_Resources.htm");
P.fA("Working with Source Control Management Software","Working_with_Source_Control_Management_Software.htm");
P.fA("Referencing Developer Installation Manifests (DIMs)","referencing_DIMs.htm");
P.fA("Adding a DIM Reference","adding_DIM.htm");
P.fA("Customizing a DIM Reference","customizing_DIM.htm");
P.fA("Removing a DIM Reference","removing_DIM.htm");
P.fA("Creating a Shortcut to a File within a DIM Reference","creating_shortcut_DIM.htm");
P.fA("Using FLEXnet Connect","using_update_service.htm");
P.fA("Checking for InstallAnywhere Update Notifications","checking_updates.htm");
P.fA("Installing InstallAnywhere Updates","installing_updates.htm");
P.fA("Integrating FLEXnet Connect with Your Product","integrating_update_service.htm");
P.fA("Adding an Enable Update Notifications Action","adding_usaction.htm");
P.fA("Customizing an Enable Update Notifications Action","customizing_usaction.htm");
P.fA("Removing an Enable Update Notifications Action","removing_usaction.htm");
P.fA("Determining a Successful Installation","Determining_a_Successful_Installation.htm");
P.fA("Troubleshooting Installers","Troubleshooting_Installers.htm");
P.fA("During Installer Development","During_Installer_Development.htm");
P.fA("Post Development","Post_Development.htm");
P.fA("Debugging a Win32 installer","Debugging_a_Win32_installer.htm");
P.fA("Debugging a Unix/Linux installer","Debugging_a_Unix_Linux_installer.htm");
P.fA("Debugging a Mac OS X Installer","Debugging_a_Mac_OS_X_Installer_.htm");
P.fA("Debugging a Pure Java Installer","Debugging_a_Pure_Java_Installer.htm");
P.fA("Debugging LaunchAnywhere Launched Executables","Debugging_LaunchAnywhere_Launched_Executables_.htm");
P.fA("Reviewing Debug Information","Reviewing_Debug_Information.htm");
P.fA("Using Output Debug Information Actions","Using_Output_Debug_Information_Actions.htm");
P.fA("Debugging Using Display Message Panel","Installing_Updatesbs.htm");
P.fA("Defining Installer Exit Codes","InstallAnywhere%208.0-07-44.htm");
P.fA("Project Wizard","project_wizardbw.htm");
P.fA("New Project","New_Project.htm");
P.fA("Set Info","Set_Info.htm");
P.fA("Add Files","Add_Files.htm");
P.fA("Choose Main","Choose_Main.htm");
P.fA("Set Classpath","Set_Classpath.htm");
P.fA("Build Installer","Build_Installer.htm");
P.fA("Try Installer","Try_Installer.htm");
P.fA("Menus","menus.htm");
P.fA("File","File.htm");
P.fA("Edit","Edit.htm");
P.fA("Preferences","Preferences.htm");
P.fA("General Settings","General_Settings.htm");
P.fA("Source Paths","Source_Paths.htm");
P.fA("Updates","Update.htm");
P.fA("Designer Colors","Designer_Colors.htm");
P.fA("Registration","Registration1.htm");
P.fA("Wizard","Start_Wizard.htm");
P.fA("Help","Help1.htm");
P.fA("Actions and Rules","actions_rules.htm");
P.fA("Install Actions","Install_Actions.htm");
P.fA("General Actions","General_Actions.htm");
P.fA("Panel Actions","Panel_Actions.htm");
P.fA("Console Actions","Console_Actions.htm");
P.fA("Common Properties","Common_Properties.htm");
P.fA("Panel Action Settings","Panel_Action_Settings.htm");
P.fA("Image Settings","Image_Settings.htm");
P.fA("Label Settings","Label_Settings.htm");
P.fA("Help","Help3.htm");
P.fA("Additional Action Information","Additional_Action_Information.htm");
P.fA("LaunchAnywhere","LaunchAnywhere1.htm");
P.fA("Manifest Files","Manifest_Files.htm");
P.fA("Get User Input Panels\u00a0","Get_User_Input_Panels.htm");
P.fA("Rules","Rules.htm");
P.fA("Variables","variables.htm");
P.fA("Setting InstallAnywhere Variables","Setting_InstallAnywhere_Variables.htm");
P.fA("Standard InstallAnywhere Variables","Standard_InstallAnywhere_Variables.htm");
P.fA("Checking the Value of a Variable","Checking_the_Value_of_an_InstallAnywhere_Variable.htm");
P.fA("LAX Properties","LAX_Properties.htm");
P.fA("Magic Folders and Variables","Magic_Folders_and_InstallAnywhere_Variables.htm");
P.fA("Custom Code","custom_code.htm");
P.fA("Custom Code and Variables","Custom_Code_and_InstallAnywhere_Variables.htm");
P.fA("Packaging and Executing Custom Code","How_to_Package_and_Execute_Custom_Code_with_an_Installer.htm");
P.fA("Internationalizing Custom Code","Internationalizing_Custom_Code.htm");
P.fA("Plug-ins","Packaging_Custom_Code_as_a_Plug_in_.htm");
P.fA("Uninstaller","uninstallercs.htm");
P.fA("Custom Code","Custom_Code1.htm");
P.fA("InstallAnywhere Variables","InstallAnywhere_Variables1.htm");
P.fA("Feature Uninstall","Feature_Uninstall.htm");
P.fA("Uninstaller for Merge Modules and Multiple Products","Uninstaller_for_Merge_Modules_and_Multiple_Products.htm");
P.fA("Merge Modules and Templates","merge_modules_templates.htm");
P.fA("Merge Modules","Merge_Modules1.htm");
P.fA("Templates","Templates1.htm");
P.fA("Silent and Console Installers","silent_console_installers.htm");
P.fA("Silent Installers","Silent_Installers.htm");
P.fA("Console Installers","Console_Installers.htm");
P.fA("Troubleshooting","troubleshooting.htm");
P.fA("Unix","Unix.htm");
P.fA("Mac OS X","Magic_Folder_Matrix_for_Mac_OS_X.htm");
P.fA("z/OS and OS/390","z_OS_and_OS_390.htm");
P.fA("Build Tools","build_tools.htm");
P.fA("Exit Codes","Examples.htm");
P.fA("ANT Build Integration","ANT_Build_Integration.htm");
P.fA("Localization","localizationdq.htm");
P.fA("Dynamic and Static Text","Dynamic_and_Static_Text.htm");
P.fA("Localization and the Internationalized Designer","Localization_and_the_Internationalized_Designer.htm");
P.fA("Specific Localization Concerns","Specific_Localization_Concerns.htm");
P.fA("Localizing Resources","Localizing_Resources.htm");
P.fA("Localizing Custom installer Labels","Localizing_Custom_installer_Labels.htm");
P.fA("Localizing Custom Code","Localizing_Custom_Code.htm");
P.fA("Localizing the Get User Input Panels","Localizing_the_Get_User_Input_Panels.htm");
P.fA("Best Practices for Localizing","Best_Practices_for_Localizing.htm");
P.fA("Language Codes","Language_Codes.htm");
P.fA("Localizable Elements","Localizable_Elements.htm");
P.fA("Localizing Items in the Installer","localizing%20items.htm");
}
